### ISSUE TITLE
CMake build fails on Windows

### ISSUE THREAD

**Issue by michael-hart** [zeromq/cppzmq#199] opened 2018-04-08 17:28 UTC
Both on MinGW and using MSVC (Visual Studio 2017), I have build failures from being unable to build googletest. In both cases, removing the tests folder and the line from the top-level CMakeLists.txt to include the tests directory has caused successful compilation. I have included the build output as a pastebin.

https://pastebin.com/2sq2jv7N

**Comment by michael-hart** [comment] 2018-04-08 17:41
Seems related to google/googletest#1373 

In this issue thread, it is suggested to use:
```
cmake .. -DCMAKE_CXX_FLAGS=/D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING
```
This causes INSTALL to build correctly, but unit_tests still fails. The error log is here:
https://pastebin.com/kXMTT8rg

**Comment by kurdybacha** [comment] 2018-04-08 21:55
@michael-hart for reporting this and logs, they are very useful.
I think problem is here:
`error C2079: 'endpoint' uses undefined class 'std::array<char,100>'
and is caused by my last commit.
I do not have Windows machine with VS right now to verify by I believe that if you add:
`#include<array>` on top of poller.cpp that should fix the issue.
I will verify tomorrow.

**Comment by kurdybacha** [comment] 2018-04-09 16:49
#200 that has been merged to trunk might address the issue. Pending verification on Windows with VS.

**Comment by sigiesec** [comment] 2018-04-09 18:06
Appveyor CI with various VS versions, and maybe also gcc on mingw and cygwin should be added to catch such issues earlier. I planned to do this, but did not find the time yet.

**Comment by michael-hart** [comment] 2018-04-09 21:14
I've pulled from master and tried again. The flag I wrote in an earlier comment was still required, and the build still unfortunately fails. I've included the log:

https://pastebin.com/eavZa900

**Comment by kurdybacha** [comment] 2018-04-10 23:34
@michael-hart, I have just setup Windows machine with VS 2017 and can reproduce the issue.
Two problems with gtest:
1. Deprecation warning causing errors. You have already found a way to disable warning with `-DCMAKE_CXX_FLAGS=//D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING` or just `-DCMAKE_CXX_FLAGS=//w`.
2. By default, new Visual Studio projects link the C runtimes dynamically but Google Test links them statically. Workaround for now would be to build cppzmq with `-Dgtest_force_shared_crt=ON`.

My full commands to build cppzmq with cmake on Windows were:

```
$ cd cppzmq
$ mkdir build
$ cd build
$ cmake -DCMAKE_CXX_FLAGS=\/w -DCMAKE_PREFIX_PATH=/c/Users/Pawel/Repo/libzmq/build -DENABLE_DRAFTS=1 -Dgtest_force_shared_crt=ON ..
$ cmake --build .
```
Hopefully that will unblock you for now. We will keep this issue open until we figure out how to fix it properly.

**Comment by kurdybacha** [comment] 2018-04-17 09:38
@bluca @sigiesec you can close this issue now, please

**Closed** 2018-04-17 09:49 UTC
