### ISSUE TITLE
Bug? Undefined reference to std::_throw_out_of_range while linking (libzmq.so) 

### ISSUE THREAD

**Issue by samacumen** [zeromq/cppzmq#180] opened 2018-01-24 19:42 UTC
I am cross compiling on my Ubuntu 16.04LTS with the help of Raspberry Pi's toolchain (arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++ compiler).

I get the following linker error while linking a "cpp project" for binary. Does not happen when generating a static library (.a), but only when generating a cross compiled binary with ZMQ. I checked the dependencies, all seem OK. Is this a bug with g++ linker or something on ZMQ side?

Anybody else faced this? Any lead?

**OUTPUT:**
```
[100%] Linking CXX executable coilcharger
rpi/rootfs/usr/lib/arm-linux-gnueabihf/libzmq.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
collect2: error: ld returned 1 exit status

Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by bluca** [comment] 2018-01-24 19:51
That's a symbol from the standard library, so your script is most likely missing some dependencies

**Comment by samacumen** [comment] 2018-01-24 19:58
Thanks for your reply. But that's strange I seem to build every other C++ project with it until today (using this toolchain almost daily for a year now).

This is what I use:
https://github.com/raspberrypi/tools/tree/master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64

I use the bin/arm-linux-gnueabihf-g++ ARM compiler. Unable to generate a C++ cross-compiled ARM binary using this. Could it be some mismatch with ZMQ's std library requirement.

Any lead?

**Comment by bluca** [comment] 2018-01-24 20:15
As you can see that symbol is not used here or in libzmq, so the problem is in your toolchain somewhere - if I had to take a wild guess I'd say mismatching standard libraries or other dependencies

**Comment by samacumen** [comment] 2018-01-24 21:41
Thanks for the lead. I just find that 'arm-linux-gnueabihf-gcc' is 4.8.3 and that is the issue. Probably need to update the toolchain to a higher revision.

An issue already raised here, for your reference:
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=122557

**Comment by bluca** [comment] 2018-01-24 22:30
Ok great, thank for the update, will close this now then.

**Closed by bluca** 2018-01-24 22:30 UTC
